name: Build Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show repository
        run: |
          pwd
          ls -lah
          echo "----- Dockerfiles -----"
          find . -name "Dockerfile" -exec ls -lh {} \;
          echo "----- Root Dockerfile -----"
          cat ./Dockerfile

      - name: Build image
        run: |
          docker build \
            --progress=plain \
            -f ./Dockerfile \
            .